"""Make content_id non-nullable in FlagReport

Revision ID: 1e49e7148619
Revises: ebc55f418c2c
Create Date: 2025-05-11 09:20:49.138876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e49e7148619'
down_revision = 'ebc55f418c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flag_report', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flag_report', schema=None) as batch_op:
        batch_op.alter_column('content_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
