"""Your migration message

Revision ID: 213e49b6c259
Revises: 
Create Date: 2025-05-05 17:23:49.528042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213e49b6c259'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=True))
        batch_op.drop_column('flagged')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_flagged')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flagged', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_flagged')

    # ### end Alembic commands ###
