"""Initial migration

Revision ID: 23ada46ef4bd
Revises: c7d96fb61c18
Create Date: 2025-05-23 22:10:50.918541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ada46ef4bd'
down_revision = 'c7d96fb61c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
