"""Add answered_by column to Question

Revision ID: 2e07182df3f0
Revises: 1e49e7148619
Create Date: 2025-05-11 11:17:01.906375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e07182df3f0'
down_revision = '1e49e7148619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['answered_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('answered_by')

    # ### end Alembic commands ###
