"""Add media_type to Post

Revision ID: 58877dc17f9e
Revises: 27bd5e04d4c5
Create Date: 2025-05-07 03:35:06.959937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58877dc17f9e'
down_revision = '27bd5e04d4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=True))
        batch_op.alter_column('media_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('media_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
