"""Ensure all models are detected

Revision ID: 5d109384a558
Revises: 23ada46ef4bd
Create Date: 2025-05-23 22:24:04.672517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d109384a558'
down_revision = '23ada46ef4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
