"""new model changes

Revision ID: 6fd6093356a9
Revises: 58877dc17f9e
Create Date: 2025-05-08 14:07:35.462431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd6093356a9'
down_revision = '58877dc17f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.drop_column('member_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_count', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
