"""Add doctor_id to Question

Revision ID: b36950d58599
Revises: 27bd5e04d4c5
Create Date: 2025-05-07 06:16:46.459766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b36950d58599'
down_revision = '27bd5e04d4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('question_answered_by_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['doctor_id'], ['id'])
        batch_op.drop_column('answered_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_answered_by_fkey', 'user', ['answered_by'], ['id'])
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
