"""Initial migration

Revision ID: c7d96fb61c18
Revises: 294ec7b2c64b
Create Date: 2025-05-23 22:08:41.772692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d96fb61c18'
down_revision = '294ec7b2c64b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
